package aquaguard;

import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dreel
 */
public class AquaGuardApp extends javax.swing.JFrame {
    int mouseX, mouseY;
    CardLayout cl;
    /**
     * Creates new form AquaGuardApp
     */
    public AquaGuardApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        dragWindow(this);
        cl = (CardLayout)(cards.getLayout());
        this.setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        
    }
    
    public void dragWindow(JFrame frame){
        
        frame.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                 mouseX = e.getX();
                 mouseY = e.getY();
            }
        });

        frame.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent e) {
                // Get the new position of the window
                int newX = e.getXOnScreen() - mouseX;
                int newY = e.getYOnScreen() - mouseY;

                // Set the new position of the window
                frame.setLocation(newX, newY);
            }
        });

    }
    
    public void bubblePop(){
        String soundName = "src/Audio/bubblePop.wav";    
        AudioInputStream audioInputStream = null;
        
        try {
            audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(AquaGuardApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AquaGuardApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        Clip clip = null;
        try {
            clip = AudioSystem.getClip();
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AquaGuardApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            clip.open(audioInputStream);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AquaGuardApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AquaGuardApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        FloatControl volume = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
        volume.setValue(-20);
        System.out.println(volume.getMinimum());
        clip.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        exitBTN = new javax.swing.JLabel();
        minimiseBTN = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        topBar = new javax.swing.JPanel();
        homeBTN = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        cards = new javax.swing.JPanel();
        loginCard = new javax.swing.JPanel();
        usernameInputField = new Sections.Main.inputField();
        passwordInputField = new Sections.Main.inputField();
        loginBTN = new javax.swing.JLabel();
        createAccountBTN = new javax.swing.JLabel();
        loginErrorLabel = new javax.swing.JLabel();
        signupCard = new javax.swing.JPanel();
        signupUsernameInputField = new Sections.Main.inputField();
        signupPasswordInputField = new Sections.Main.inputField();
        SignupBTN = new javax.swing.JLabel();
        signupLoginBTN = new javax.swing.JLabel();
        signupErrorLabel = new javax.swing.JLabel();
        confirmPasswordInputField = new Sections.Main.inputField();
        homeCard = new javax.swing.JPanel();
        descriptionText = new javax.swing.JLabel();
        shoppingBTN = new javax.swing.JLabel();
        FishFallBTN = new javax.swing.JLabel();
        AdoptionBTN = new javax.swing.JLabel();
        fishFallSection1 = new Sections.FishFall.FishFallSection();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aqua Guard");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1500, 950));
        setMinimumSize(new java.awt.Dimension(1500, 950));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 900));

        titleBar.setBackground(new java.awt.Color(1, 187, 187));
        titleBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 187, 187), 5));

        exitBTN.setBackground(new java.awt.Color(49, 122, 139));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBTN.setText("X");
        exitBTN.setMaximumSize(new java.awt.Dimension(40, 40));
        exitBTN.setMinimumSize(new java.awt.Dimension(40, 40));
        exitBTN.setOpaque(true);
        exitBTN.setPreferredSize(new java.awt.Dimension(40, 40));
        exitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBTNMouseClicked(evt);
            }
        });

        minimiseBTN.setBackground(new java.awt.Color(33, 86, 138));
        minimiseBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        minimiseBTN.setForeground(new java.awt.Color(255, 255, 255));
        minimiseBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimiseBTN.setText("-");
        minimiseBTN.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        minimiseBTN.setMaximumSize(new java.awt.Dimension(40, 40));
        minimiseBTN.setMinimumSize(new java.awt.Dimension(40, 40));
        minimiseBTN.setOpaque(true);
        minimiseBTN.setPreferredSize(new java.awt.Dimension(40, 40));
        minimiseBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimiseBTNMouseClicked(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Aqua Guard");

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AquaGuardLogo.png"))); // NOI18N

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconLabel)
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimiseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minimiseBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        topBar.setBackground(new java.awt.Color(0, 255, 255));
        topBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 187, 187), 5));
        topBar.setMaximumSize(new java.awt.Dimension(1500, 100));
        topBar.setMinimumSize(new java.awt.Dimension(1500, 100));
        topBar.setPreferredSize(new java.awt.Dimension(1500, 100));

        homeBTN.setVisible(false);
        homeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/homeBTN.png"))); // NOI18N
        homeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBTNMouseClicked(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Login");

        logoutLabel.setVisible(false);
        logoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addComponent(homeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cards.setBackground(new java.awt.Color(49, 122, 139));
        cards.setMaximumSize(new java.awt.Dimension(1500, 800));
        cards.setMinimumSize(new java.awt.Dimension(1500, 800));
        cards.setPreferredSize(new java.awt.Dimension(1500, 800));
        cards.setLayout(new java.awt.CardLayout());

        loginCard.setOpaque(false);

        usernameInputField.setTag("Username");

        passwordInputField.setTag("Password");

        loginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/loginBTN.png"))); // NOI18N
        loginBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBTNMouseClicked(evt);
            }
        });

        createAccountBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/SignupButton.png"))); // NOI18N
        createAccountBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountBTNMouseClicked(evt);
            }
        });

        loginErrorLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        loginErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginErrorLabel.setText("Error Message Goes Here");

        javax.swing.GroupLayout loginCardLayout = new javax.swing.GroupLayout(loginCard);
        loginCard.setLayout(loginCardLayout);
        loginCardLayout.setHorizontalGroup(
            loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardLayout.createSequentialGroup()
                .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccountBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(loginCardLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginCardLayout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        loginCardLayout.setVerticalGroup(
            loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAccountBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        cards.add(loginCard, "login");

        signupCard.setOpaque(false);

        signupUsernameInputField.setTag("Username");

        signupPasswordInputField.setTag("Password");

        SignupBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/SignupButton.png"))); // NOI18N
        SignupBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupBTNMouseClicked(evt);
            }
        });

        signupLoginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/loginBTN.png"))); // NOI18N
        signupLoginBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLoginBTNMouseClicked(evt);
            }
        });

        signupErrorLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        signupErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        signupErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupErrorLabel.setText("Error Message Goes Here");

        confirmPasswordInputField.setTag("Confirm Password");

        javax.swing.GroupLayout signupCardLayout = new javax.swing.GroupLayout(signupCard);
        signupCard.setLayout(signupCardLayout);
        signupCardLayout.setHorizontalGroup(
            signupCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupCardLayout.createSequentialGroup()
                .addGroup(signupCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmPasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(signupCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(signupCardLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(SignupBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signupCardLayout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addGroup(signupCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(signupPasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(signupUsernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        signupCardLayout.setVerticalGroup(
            signupCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupCardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(signupErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupUsernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupPasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SignupBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signupLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        cards.add(signupCard, "signup");

        homeCard.setMaximumSize(new java.awt.Dimension(1500, 800));
        homeCard.setMinimumSize(new java.awt.Dimension(1500, 800));
        homeCard.setOpaque(false);

        descriptionText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AquaGuard Description.png"))); // NOI18N

        shoppingBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/Shopping.png"))); // NOI18N
        shoppingBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shoppingBTNMouseClicked(evt);
            }
        });

        FishFallBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/Fish Fall.png"))); // NOI18N
        FishFallBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FishFallBTNMouseClicked(evt);
            }
        });

        AdoptionBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buttons/Adoption.png"))); // NOI18N

        javax.swing.GroupLayout homeCardLayout = new javax.swing.GroupLayout(homeCard);
        homeCard.setLayout(homeCardLayout);
        homeCardLayout.setHorizontalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeCardLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(shoppingBTN)
                .addGap(18, 18, 18)
                .addComponent(FishFallBTN)
                .addGap(18, 18, 18)
                .addComponent(AdoptionBTN)
                .addGap(192, 192, 192))
        );
        homeCardLayout.setVerticalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoppingBTN)
                    .addComponent(FishFallBTN)
                    .addComponent(AdoptionBTN))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        cards.add(homeCard, "home");
        cards.add(fishFallSection1, "fishFall");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(topBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shoppingBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoppingBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_shoppingBTNMouseClicked

    private void FishFallBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FishFallBTNMouseClicked
        cl.show(cards,"fishFall");
        nameLabel.setText("FishFall");
        bubblePop();
    }//GEN-LAST:event_FishFallBTNMouseClicked

    private void homeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBTNMouseClicked
        cl.show(cards,"home");
        nameLabel.setText("Home");
        bubblePop();
    }//GEN-LAST:event_homeBTNMouseClicked

    private void exitBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitBTNMouseClicked

    private void minimiseBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseBTNMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimiseBTNMouseClicked

    private void loginBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTNMouseClicked
        cl.show(cards,"home");
        nameLabel.setText("Home");
        homeBTN.setVisible(true);
        logoutLabel.setVisible(true);
    }//GEN-LAST:event_loginBTNMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        cl.show(cards,"login");
        nameLabel.setText("Login");
        homeBTN.setVisible(false);
        logoutLabel.setVisible(false);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void SignupBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupBTNMouseClicked

    private void createAccountBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountBTNMouseClicked
        cl.show(cards,"signup");
        nameLabel.setText("Signup");
    }//GEN-LAST:event_createAccountBTNMouseClicked

    private void signupLoginBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLoginBTNMouseClicked
        cl.show(cards,"login");
        nameLabel.setText("Login");
    }//GEN-LAST:event_signupLoginBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AquaGuardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AquaGuardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AquaGuardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AquaGuardApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AquaGuardApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdoptionBTN;
    private javax.swing.JLabel FishFallBTN;
    private javax.swing.JLabel SignupBTN;
    private javax.swing.JPanel cards;
    private Sections.Main.inputField confirmPasswordInputField;
    private javax.swing.JLabel createAccountBTN;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JLabel exitBTN;
    private Sections.FishFall.FishFallSection fishFallSection1;
    private javax.swing.JLabel homeBTN;
    private javax.swing.JPanel homeCard;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel loginBTN;
    private javax.swing.JPanel loginCard;
    private javax.swing.JLabel loginErrorLabel;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel minimiseBTN;
    private javax.swing.JLabel nameLabel;
    private Sections.Main.inputField passwordInputField;
    private javax.swing.JLabel shoppingBTN;
    private javax.swing.JPanel signupCard;
    private javax.swing.JLabel signupErrorLabel;
    private javax.swing.JLabel signupLoginBTN;
    private Sections.Main.inputField signupPasswordInputField;
    private Sections.Main.inputField signupUsernameInputField;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topBar;
    private Sections.Main.inputField usernameInputField;
    // End of variables declaration//GEN-END:variables
}
