/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aquaguard;

import aquaguard.AquaGuard;
import aquaguard.User;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Timer;

/**
 *
 * @author Dreel
 */
public class FishFallGame extends javax.swing.JPanel {
    int screenWidth = 600;
    int screenHeight = 750;
    int tileSize = 50;
    User pl;;
    protected char direction;
    
    Timer timer;
    int dropSpeed = 500;
    int score = 0;
    /**
     * Creates new form FishFallGame
     */
    public FishFallGame() {
        this.pl = AquaGuardApp.currentUser;
        initComponents();
        setFocusable(true);
        addKeyListener(new MyKeyAdapter());
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        draw(g);
    }
    
    public void draw(Graphics g){
   
        // draw Background
        g.setColor(new Color(0, 74, 173));
        g.fillRect(0,0,600,750);
        
        // draw vertical lines
        for(int i = tileSize; i < screenHeight; i+= tileSize){
            g.setColor(new Color(255, 255, 255));
            g.drawRect(0, i, screenWidth, 0);
        }
        
        //draw horizontal lines
        for(int i = tileSize; i < screenHeight; i+= tileSize){
            g.setColor(new Color(255, 255, 255));
            g.drawRect(i, 0, 0, screenHeight);
        }
        
        //draw basket
        g.setColor(new Color(255, 0,255));
        g.fillRect(pl.getX(), pl.getY(), tileSize, tileSize);
    }
    
    public void move(){
        if (direction == 'L' && pl.getX() > 0){
            pl.setX(pl.getX() - tileSize);
        }
        else if(direction == 'R' && pl.getX() < (screenWidth - tileSize)){
            pl.setX(pl.getX() + tileSize);
        }
    }
    
    public class MyKeyAdapter extends KeyAdapter {
    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                direction = 'L'; // set direction to L
                move();
                repaint();
                break;
            case KeyEvent.VK_RIGHT:
                direction = 'R'; // set direction to L 
                move();
                repaint();
                break;
            case KeyEvent.VK_A:
                direction = 'L'; // set direction to L 
                move();
                repaint();
                break;
            case KeyEvent.VK_D:
                direction = 'R'; // set direction to L 
                move();
                repaint();
                break;
        }
     
    }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(33, 86, 138));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        setMaximumSize(new java.awt.Dimension(600, 750));
        setMinimumSize(new java.awt.Dimension(600, 750));
        setPreferredSize(new java.awt.Dimension(600, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
