/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sections.Fishfall;

/**
 *
 * @author Jordan Dreelan x23150076
 */
public class LeaderboardPlayer extends javax.swing.JPanel {
    private User u;
    private int ranking;
    /**
     * Creates new form LeaderboardPlayer
     */
    
    //constructor for LeaderboardPlayer
    public LeaderboardPlayer() {
        initComponents();
    }
    
    //method to invert the color of the background used so every 2nd can be a different color for nicer look
    public void invertColor(){
        usernameLabel.setBackground(new java.awt.Color(0,255,255));
        scoreLabel.setBackground(new java.awt.Color(0,255,255));
    }
    
    //method to display the users stats
    public void displayUser(int rank, User u){
        this.ranking = rank;
        this.u = u;
        
        usernameLabel.setText("#" + ranking + " " + u.getUsername());
        scoreLabel.setText("" + u.getHighScore());
    }
    
    //method to check if there is a user attatched to the LeaderboardPlayer
    public boolean checkUser(User u){
        if(this.u == u && this.u != null){
            return true;
        }else{
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 50));
        setMinimumSize(new java.awt.Dimension(400, 50));
        setPreferredSize(new java.awt.Dimension(400, 50));

        usernameLabel.setBackground(new java.awt.Color(1, 187, 187));
        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("#1 Username");
        usernameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        usernameLabel.setOpaque(true);

        scoreLabel.setBackground(new java.awt.Color(1, 187, 187));
        scoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setText("Score");
        scoreLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
