/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sections.Main;

/**
 *
 * @author Dreel
 */
public class InputField extends javax.swing.JPanel {

    /**
     * Creates new form inputField
     */
    public InputField() {
        initComponents();
    }
    
    public void setTag(String tag){
        tagLabel.setText(tag);
    }
    
    public String getText(){
        return inputField.getText();
    }
    
    public void setText(String str){
        inputField.setText(str);
    }
    
    public void clearText(){
        inputField.setText("");
    }
    
    @Override
    public void disable(){
        inputField.setEditable(false);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginInputDisabled.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer = new javax.swing.JLayeredPane();
        background = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1150, 100));
        setMinimumSize(new java.awt.Dimension(1150, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1150, 100));

        Layer.setMaximumSize(new java.awt.Dimension(1150, 100));
        Layer.setMinimumSize(new java.awt.Dimension(1150, 100));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginInput.png"))); // NOI18N

        tagLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        tagLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagLabel.setText("Tag");

        inputField.setOpaque(false);
        inputField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        inputField.setBorder(null);
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        Layer.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Layer.setLayer(tagLabel, javax.swing.JLayeredPane.PALETTE_LAYER);
        Layer.setLayer(inputField, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout LayerLayout = new javax.swing.GroupLayout(Layer);
        Layer.setLayout(LayerLayout);
        LayerLayout.setHorizontalGroup(
            LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayerLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(background)
            .addGroup(LayerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(tagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LayerLayout.setVerticalGroup(
            LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
            .addGroup(LayerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private javax.swing.JLabel background;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel tagLabel;
    // End of variables declaration//GEN-END:variables
}
