/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sections.Main;

/**
 *
 * @author Dreel
 */
public class inputField extends javax.swing.JPanel {

    /**
     * Creates new form inputField
     */
    public inputField() {
        initComponents();
    }
    
    public void setTag(String tag){
        tagLabel.setText(tag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer = new javax.swing.JLayeredPane();
        background = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1150, 100));
        setMinimumSize(new java.awt.Dimension(1150, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1150, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Layer.setMaximumSize(new java.awt.Dimension(1150, 100));
        Layer.setMinimumSize(new java.awt.Dimension(1150, 100));
        Layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginInput.png"))); // NOI18N
        Layer.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        tagLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        tagLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagLabel.setText("Tag");
        Layer.setLayer(tagLabel, javax.swing.JLayeredPane.PALETTE_LAYER);
        Layer.add(tagLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 284, 88));

        inputField.setOpaque(false);
        inputField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        inputField.setBorder(null);
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });
        Layer.setLayer(inputField, javax.swing.JLayeredPane.PALETTE_LAYER);
        Layer.add(inputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 6, 730, 88));

        add(Layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private javax.swing.JLabel background;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel tagLabel;
    // End of variables declaration//GEN-END:variables
}
