/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sections.Main;

import Sections.Fishfall.User;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Dreel
 */
public class SettingsPage extends javax.swing.JPanel {
    private CardLayout cl;
    private User currentUser;
    public SettingsPage() {
        initComponents();
    }
    
    public void setUser(User u){
        this.currentUser = u;
    }
    
    public void initUser(){
        accountNameField.setText(currentUser.getUsername().toString());
        accountHighScoreField.setText(String.valueOf(currentUser.getHighScore()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cards = new javax.swing.JPanel();
        accountCard = new javax.swing.JPanel();
        accountNameField = new Sections.Main.InputField();
        accountHighScoreField = new Sections.Main.InputField();
        sideBar = new javax.swing.JPanel();
        accountPgLabel = new javax.swing.JLabel();
        accountPgLabel1 = new javax.swing.JLabel();
        accountPgLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1500, 800));
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1500, 800));

        Cards.setOpaque(false);
        Cards.setLayout(new java.awt.CardLayout());

        accountCard.setOpaque(false);

        accountNameField.setTag("Username");
        accountNameField.disable();

        accountHighScoreField.setTag("Highscore");
        accountHighScoreField.disable();

        javax.swing.GroupLayout accountCardLayout = new javax.swing.GroupLayout(accountCard);
        accountCard.setLayout(accountCardLayout);
        accountCardLayout.setHorizontalGroup(
            accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountCardLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountHighScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        accountCardLayout.setVerticalGroup(
            accountCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountCardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(accountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountHighScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        Cards.add(accountCard, "card2");

        sideBar.setBorder(new MatteBorder(0, 0, 0, 5, new Color(46, 116, 132)));
        sideBar.setBackground(new java.awt.Color(0, 255, 255));
        sideBar.setMaximumSize(new java.awt.Dimension(300, 800));
        sideBar.setMinimumSize(new java.awt.Dimension(300, 800));
        sideBar.setPreferredSize(new java.awt.Dimension(300, 800));

        accountPgLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        accountPgLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountPgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountPgLabel.setText("Account ");

        accountPgLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        accountPgLabel1.setForeground(new java.awt.Color(255, 255, 255));
        accountPgLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountPgLabel1.setText("Change Pin");

        accountPgLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        accountPgLabel2.setForeground(new java.awt.Color(255, 255, 255));
        accountPgLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountPgLabel2.setText("Delete Account");

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountPgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountPgLabel1)
                    .addComponent(accountPgLabel2))
                .addGap(21, 21, 21))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(accountPgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountPgLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountPgLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sideBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JPanel accountCard;
    private Sections.Main.InputField accountHighScoreField;
    private Sections.Main.InputField accountNameField;
    private javax.swing.JLabel accountPgLabel;
    private javax.swing.JLabel accountPgLabel1;
    private javax.swing.JLabel accountPgLabel2;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
